// services.js

const projectsData = [
  {
    name: "Project 1",
    description: <p><strong>AES-Encryption-Algorithm</strong> A simple AES Encryption Algorithm in Java that can encrypt ASCII printable characters (character code 32-126). Algorithm includes two classes: one for generating encryption and decryption keys using RNG methodology, and the second class use to encrypt and decrypt .xlsx file<br /><strong>Skills Utilized:</strong> Java Servlet, MySQL, HTML, CSS & Js</p>,
    svn_url: "http://project1-url.com",
    stargazers_count: 10,
    languages_url: "http://languages1-url.com",
    pushed_at: "2022-01-01T12:00:00Z",
  },
  {
    name: "Project 2",
    description: <p><strong>E-Commerce</strong> An e-commerce web application serves as a robust platform facilitating seamless interaction between customers and businesses, enabling the sale of products or services online. Through intuitive functionalities including registration, login, cart management, billing, and secure payment processing, users can effortlessly navigate and engage with the platform.<br/><strong>Skills Utilized:</strong> React Js, MySQL, CSS</p>,
    svn_url: "http://project4-url.com",
    stargazers_count: 40,
    languages_url: "http://languages4-url.com",
    pushed_at: "2022-04-02T12:00:00Z",
  },
  {
    name: "Project 3",
    description: <p><strong>Student Management</strong> A student management system stores and tracks students' workload, personal information, grades, record, and more. It's a means of streamlining the work and tracking all the data generated by a student, consolidating everything into one system rather than multiple records.</p>,
    svn_url: "http://project4-url.com",
    stargazers_count: 40,
    languages_url: "http://languages4-url.com",
    pushed_at: "2022-04-02T12:00:00Z",
  },
  {
    name: "Project 4",
    description: <p><strong>Portfolio</strong> Crafted with precision using HTML and React.js, my portfolio stands as a polished showcase of skills and achievements. Now available for sale online, it offers individuals and businesses a professionally designed platform to highlight their expertise and attract potential clients or employers.</p>,
    svn_url: "http://project3-url.com",
    stargazers_count: 30,
    languages_url: "http://languages3-url.com",
    pushed_at: "2022-03-02T12:00:00Z",
  },
  {
    name: "Project 5",
    description: <p><strong>Event Management</strong> A centralized academic events portal simplifies access to crucial information like workshop dates, locations, and themes, empowering students, faculty, and researchers to engage more effectively. By offering a comprehensive platform, it reduces time spent searching across various sources, promoting collaboration and ensuring no vital opportunities are missed. Ultimately, it enhances participation in academic activities, fostering research, innovation, and networking.<br /><strong>Skills Utilized:</strong> PHP, MySQL, HTML, CSS & Js</p>,
    svn_url: "http://project2-url.com",
    stargazers_count: 20,
    languages_url: "http://languages2-url.com",
    pushed_at: "2022-02-02T12:00:00Z",
  },
 
  


];

export default projectsData;
